export const skills = {
  alienInvestigation: 'Alien Investigation',
  behavioral: 'Behavioral',
  bureaucracy: 'Bureaucracy',
  computer: 'Computer',
  criminalInvestigation: 'Criminal Investigation',
  evidenceCollection: 'Evidence Collection',
  medical: 'Medical',
  occultInvestigation: 'Occult Investigation',
  observation: 'Observation',
  sciences: 'Sciences',
  subterfuge: 'Subterfuge'
}

export const stats = {
  longRangeCombat: 'Long Range Combat',
  closeRangeCombat: 'Close Range Combat',
  health: 'Health',
  res: 'Res',
  cost: 'Cost'
}

export const agents = [
  {
    name: 'Agent Henderson',
    image: '/images/pr96-0006-due-agent-henderson.jpg',
    criminalInvestigation: 1,
    evidenceCollection: 3,
    observation: 2,
    sciences: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 3,
    gameEffect: 'Place a token on this card. Discard a token and look through your Bureau deck to draw any one Site that asks a MOTIVE question. Add it to your hand. Reshuffle your Bureau deck.'
  },
  {
    name: 'Section Chief Scott Blevins',
    image: '/images/xf97-0160v2-section-chief-scott-blevins.jpg',
    alienInvestigation: 1,
    bureaucracy: 3,
    criminalInvestigation: 1,
    evidenceCollection: 1,
    subterfuge: 1,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 4,
    gameEffect: 'Treat Section Chief Blevins as a RES 2 if he is in the Bureau Section. If he is in the Bureau Section, he may contribute to the Conspiracy Pool instead of the Resources Pool during the Briefing Phase.'
  },
  {
    name: 'Albert Hosteen',
    image: '/images/xf97-0161v2-albert-hosteen.jpg',
    alienInvestigation: 2,
    medical: 2,
    observation: 1,
    occultInvestigation: 4,
    subterfuge: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 4,
    gameEffect: 'Place a token on Hosteen\'s card. Discard a token to examine your opponent\'s hand. Select any one Conspiracy card in your opponent\'s hand and show it to your opponent. If your opponent plays that card at any time in the game, you may immediately ask one question about the X-File. This question may only be asked the first time the card is played.'
  },
  {
    name: 'Lt. Brian Tillman, Aubry P.D.',
    image: '/images/xf97-0164v2-lt-brian-tillman-aubry-pd.jpg',
    bureaucracy: 1,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    occultInvestigation: 1,
    sciences: 2,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword EQUIPMENT or COMBAT cards. If you use this RP, replace it during your Briefing Phase.'
  },
  {
    name: 'Agent Rich',
    image: '/images/xf97-0165v2-agent-rich.jpg',
    behavioral: 2,
    computer: 1,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    subterfuge: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword EVIDENCE COLLECTION or SUBTERFUGE cards. If you use this RP, replace it during your Briefing Phase.'
  },
  {
    name: 'Agent Lucy Kazdin',
    image: '/images/xf97-0166v2-agent-lucy-kazdin.jpg',
    alienInvestigation: 1,
    behavioral: 3,
    computer: 1,
    medical: 1,
    observation: 1,
    subterfuge: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'If one of your Agents is Abducted, you may immediately draw two cards.'
  },
  {
    name: 'Agent Jack Willis',
    image: '/images/xf97-0167v2-agent-jack-willis.jpg',
    behavioral: 2,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    occultInvestigation: 1,
    subterfuge: 1,
    longRangeCombat: 3,
    closeRangeCombat: 2,
    health: 5,
    res: 1,
    cost: 4,
    gameEffect: 'Place a token on this card. Discard a token and look through your Bureau deck to draw any one Site that asks an AFFILIATION question. Add it to your hand. Reshuffle your Bureau deck.'
  },
  {
    name: 'Inspector Phoebe Green',
    image: '/images/xf97-0168v2-inspector-phoebe-green.jpg',
    criminalInvestigation: 3,
    evidenceCollection: 2,
    observation: 3,
    sciences: 2,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 5,
    gameEffect: 'Place a token on this card. Discard a token to move Agent Fox Mulder from anywhere on the table to the Team Phoebe Green is in. Mulder may assist in any skill check made by the Team. In this manner, Mulder may assist on two Sites in one turn.'
  },
  {
    name: 'Agent Fox Mulder',
    image: '/images/xf97-0169v2-agent-fox-mulder.jpg',
    alienInvestigation: 4,
    behavioral: 3,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    observation: 2,
    occultInvestigation: 3,
    sciences: 1,
    subterfuge: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 5,
    res: 2,
    cost: 7,
    gameEffect: 'RP\'s generated by Agent Mulder must be used to purchase cards. Place three tokens on this card. Discard a token to play a Site for zero RP cost.'
  },
  {
    name: 'Agent Alex Krycek',
    image: '/images/xf97-0170v2-agent-alex-krycek.jpg',
    alienInvestigation: 3,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    sciences: 1,
    subterfuge: 4,
    longRangeCombat: 4,
    closeRangeCombat: 2,
    health: 5,
    res: 2,
    cost: 6,
    gameEffect: 'Agent Krycek allows you to choose to add to the Conspiracy Pool instead of the Resource Pool during the Briefing Phase.'
  },
  {
    name: 'Agent Nancy Spiller',
    image: '/images/xf97-0171v2-agent-nancy-spiller.jpg',
    bureaucracy: 2,
    computer: 1,
    criminalInvestigation: 1,
    evidenceCollection: 1,
    medical: 3,
    sciences: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 4,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword COMPUTER or SCIENCES cards. If you use this RP, replace it during your Briefng Phase.'
  },
  {
    name: 'Agent Dana Scully',
    image: '/images/xf97-0173v2-agent-dana-scully.jpg',
    behavioral: 1,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    medical: 4,
    observation: 2,
    occultInvestigation: 1,
    sciences: 3,
    longRangeCombat: 3,
    closeRangeCombat: 2,
    health: 4,
    res: 2,
    cost: 7,
    gameEffect: 'Place three tokens on this card. Discard a token to examnine any one Bluff card. Place Bluff card back on the Site after examining.'
  },
  {
    name: 'Dr. Charles Burk',
    image: '/images/xf97-0175v2-dr-charles-burk.jpg',
    alienInvestigation: 1,
    computer: 4,
    observation: 1,
    occultInvestigation: 2,
    sciences: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 4,
    gameEffect: 'Place one token on this card. Discard a token to negate one OCCULT Adversary.'
  },
  {
    name: 'Agent Tom Colton',
    image: '/images/xf97-0176v2-agent-tom-colton.jpg',
    behavioral: 1,
    bureaucracy: 1,
    criminalInvestigation: 2,
    sciences: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 3,
    res: 2,
    cost: 4,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword CRIMINAL INVESTIGATION or BUREAUCRACY cards. If you use this RP, replace it during your Briefing Phase.'
  },
  {
    name: 'Agent Janus, Trained Medic',
    image: '/images/xf97-0177v2-agent-janus-trained-medic.jpg',
    computer: 2,
    evidenceCollection: 1,
    medical: 3,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword MEDICAL or HEALING cards. If you use this RP, replace it during your Briefing Phase. in addition, if Janus is in the Field Section, he may "heal" one point of damage on another Agent in his Team, once per turn. This may prevent an Agent from going to the Hospital.'
  },
  {
    name: 'Agent Moe Bocks',
    image: '/images/xf97-0178v2-agent-moe-bocks.jpg',
    alienInvestigation: 2,
    bureaucracy: 1,
    criminalInvestigation: 3,
    evidenceCollection: 2,
    observation: 1,
    sciences: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 5,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword ALIEN INVESTIGATION or OCCULT INVESTIGATION cards. If you use this RP, replace it during your Briefing Phase.'
  },
  {
    name: 'Agent Reggie Purdue',
    image: '/images/xf97-0179v2-agent-reggie-purdue.jpg',
    behavioral: 1,
    computer: 2,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    observation: 2,
    subterfuge: 2,
    longRangeCombat: 2,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 5,
    gameEffect: 'Place a token on this card. Discard this token and look through your Bureau deck, to draw any one Site that asks a RESULT question. Add it to your hand. Reshuffle your Bureau Deck.'
  },
  {
    name: 'Assistant Director Walter Skinner',
    image: '/images/xf97-0180v2-assistant-director-walter-skinner.jpg',
    bureaucracy: 4,
    criminalInvestigation: 3,
    evidenceCollection: 2,
    subterfuge: 3,
    longRangeCombat: 2,
    closeRangeCombat: 3,
    health: 5,
    res: 1,
    cost: 6,
    gameEffect: 'Treat Assistant Director Skinner as a RES 3 if he is in the Bureau Section of the table.'
  },
  {
    name: 'Agent Weiss',
    image: '/images/xf97-0181v2-agent-weiss.jpg',
    computer: 1,
    criminalInvestigation: 1,
    observation: 2,
    subterfuge: 1,
    longRangeCombat: 3,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'Place a token on this card. Discard a token and look through your Bureau deck to draw any one Site that asks a METHOD question. Add it to your hand. Reshuffle your Bureau Deck.'
  },
  {
    name: 'Agent Jerry Lamana',
    image: '/images/xf97-0182v2-agent-jerry-lamana.jpg',
    bureaucracy: 2,
    computer: 3,
    criminalInvestigation: 1,
    evidenceCollection: 1,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 3,
    gameEffect: 'Once per game, when Agent Lamana is part of the Team investigating a Site in the Investigation Phase, he may force his opponent to show the cards in his hand. Lamana may then steal any one card. He may use it immediately in the investigation. You must still pay for the card. Whether you use it or not, place it in it\'s owner\'s Discard Pile at the end of the turn.'
  },
  {
    name: 'Agent Karen Kosseff, Counselor',
    image: '/images/xf97-0183v2-agent-karen-kosseff-counselor.jpg',
    behavioral: 3,
    criminalInvestigation: 1,
    evidenceCollection: 1,
    medical: 1,
    occultInvestigation: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 3,
    gameEffect: 'Place 1 RP on this card. This RP may be used to pay for any Keyword BEHAVIORAL or OBSERVATION cards. If you use this RP, replace it during your Briefing Phase.'
  },
  {
    name: 'Agent Bill Patterson',
    image: '/images/xf97-0396x1-agent-bill-patterson.jpg',
    behavioral: 3,
    criminalInvestigation: 3,
    evidenceCollection: 3,
    observation: 2,
    occultInvestigation: 1,
    subterfuge: 1,
    longRangeCombat: 2,
    closeRangeCombat: 3,
    health: 5,
    res: 2,
    cost: 6,
    gameEffect: 'Once per game, Agent Patterson may attack any Team investigating a Site as if he were an Adversary with the appropriate Activators. If a card is played that Negates him, he is placed back into his controller\'s Field. If he is reduced to zero HEALTH, he is removed from the game.'
  },
  {
    name: 'Agent Danny Pendrell',
    image: '/images/xf97-0397x1-agent-danny-pendrell.jpg',
    computer: 3,
    criminalInvestigation: 2,
    evidenceCollection: 3,
    medical: 1,
    observation: 2,
    sciences: 3,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 6,
    gameEffect: 'Place three tokens on Agent Pendrell. During a skill check, discard one token to add 1 to Agent Pendrell\'s COMPUTER, SCIENCES, or MEDICAL skill.'
  },
  {
    name: 'Agent Fred Nemhauser',
    image: '/images/xf97-0398x1-agent-fred-nemhauser.jpg',
    behavioral: 1,
    criminalInvestigation: 1,
    evidenceCollection: 1,
    longRangeCombat: 2,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 2,
    gameEffect: 'Agent Nemhauser\'s BEHAVIORAL and CRIMINAL INVESTIGATION skills are increased by one if he and Agent Patterson are on the same Team.'
  },
  {
    name: 'Agent Kreski',
    image: '/images/xf97-0399x1-agent-kreski.jpg',
    criminalInvestigation: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 0,
    cost: 1,
    gameEffect: 'Place one token on this card. Remove one token to negate a Keyword HEALING card played by your opponent.'
  },
  {
    name: 'Clyde Bruckman',
    image: '/images/xf97-0400x1-clyde-bruckman.jpg',
    criminalInvestigation: 2,
    evidenceCollection: 4,
    observation: 3,
    occultInvestigation: 3,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 5,
    gameEffect: 'Place one token on this card. Remove one token to examine an opponent\'s hand and remove one of the cards in his hand from the game.'
  },
  {
    name: 'Detective Angela White',
    image: '/images/xf97-0401x1-detective-angela-white.jpg',
    behavioral: 1,
    criminalInvestigation: 1,
    evidenceCollection: 2,
    observation: 1,
    occultInvestigation: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 3,
    gameEffect: 'If Detective White is in the same Team as Agent Mulder, they both gain a +1 to their cumulative OCCULT INVESTIGATION and CRIMINAL INVESTIGATION skills, and a -1 to their OBSERVATION and BEHAVIORAL skills.'
  },
  {
    name: 'Detective Manners',
    image: '/images/xf97-0402x1-detective-manners.jpg',
    criminalInvestigation: 1,
    evidenceCollection: 1,
    observation: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 0,
    cost: 2,
    gameEffect: 'Place two tokens on Detective Manners. Discard one token to search through your Bureau deck and add a Witness card to your hand. Show the Witness to your opponent and shuffle the deck.'
  },
  {
    name: 'Agent Bonnecaze',
    image: '/images/xf97-0520x2-agent-bonnecaze.jpg',
    bureaucracy: 2,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    longRangeCombat: 2,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 3,
    gameEffect: 'Place a token on Agent Bonnecaze. At any time during the game, discard a token to force any Agent to return to the Bureau immediately. This effect may not be used to interrupt Combat. An Agent moved in this manner may not contribute to any skill checks this turn.'
  },
  {
    name: 'Detective Glen Chao',
    image: '/images/xf97-0521x2-detective-glen-chao.jpg',
    bureaucracy: 1,
    criminalInvestigation: 1,
    evidenceCollection: 1,
    subterfuge: 2,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 0,
    cost: 3,
    gameEffect: 'An opposing Conspiracy player may pay two conspiracy points to send Detective Chao back to your Bureau if Detective Chao is investigating a Site with CRIMINAL INVESTIGATION, EVIDENCE COLLECTION of BUREAUCRAZY.'
  },
  {
    name: 'Agent Brian Fuller',
    image: '/images/xf97-0522x2-agent-brian-fuller.jpg',
    criminalInvestigation: 1,
    subterfuge: 1,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 3,
    res: 0,
    cost: 1,
    gameEffect: 'When an Agent in Fuller\'s Team is forced to go to the Hospital, Agent Fuller may immediately elect to "escort" the Agent to the Hospital. Fuller may only do this if he would not normally be required to go to the Hospital himself. No other cards may be played on an Agent that Fuller escorts. This will prevent cards from being played on the escorted Agent.'
  },
  {
    name: 'Agent Frank Burst',
    image: '/images/xf97-0523x2-agent-frank-burst.jpg',
    behavioral: 2,
    criminalInvestigation: 3,
    evidenceCollection: 2,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 3,
    gameEffect: 'Treat Agent Burst as a RES 2 if he is in the Field.'
  },
  {
    name: 'Agent Linda Caleca',
    image: '/images/xf97-0524x2-agent-linda-caleca.jpg',
    criminalInvestigation: 1,
    evidenceCollection: 1,
    observation: 1,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 0,
    cost: 1,
    gameEffect: 'Place two tokens on this card. Discard a token to draw one card from the top of your Bureau deck for zero RP cost any time you are the active player.'
  },
  {
    name: 'Lieutenant Brophy',
    image: '/images/xf97-0525x2-lieutenant-brophy.jpg',
    criminalInvestigation: 2,
    evidenceCollection: 1,
    longRangeCombat: 4,
    closeRangeCombat: 3,
    health: 5,
    res: 1,
    cost: 3,
    gameEffect: 'Agent Brophy may use MARTIAL ARTS cards. He may add 1 to any damage caused by Equipment cards attached to him that have a CLOSE RANGE COMBAT or LONG RANGE COMBAT modifier.'
  },
  {
    name: 'Deputy Barney Pastor',
    image: '/images/xf22-0001x3-deputy-barney-paster.jpg',
    behavioral: 1,
    computer: 1,
    criminalInvestigation: 2,
    evidenceCollection: 2,
    subterfuge: 2,
    longRangeCombat: 3,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'Place one token on this card.Remove a token during the Requisition Phase to search your Bureau Deck for any one Keyword WEAPON or ARMOR Equipment card and attach it to Paster at half cost (rounded up). Shuffle your Deck.'
  },
  {
    name: 'Mike Millar, NTSB',
    image: '/images/xf22-0002x3-mike-millar-ntsb.jpg',
    alienInvestigation: 1,
    bureaucracy: 2,
    computer: 3,
    evidenceCollection: 3,
    observation: 1,
    sciences: 2,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 5,
    gameEffect: 'Treat Mike Millar as a RES 2 if he is in the Field. If Millar is in the same Team as Agent Mulder and/or Agent Scully, he gains +1 to his ALIEN INVESTIGATION and OBSERVATION skills.'
  },
  {
    name: 'Agent Kautz',
    image: '/images/xf22-0003x3-agent-kautz.jpg',
    bureaucracy: 1,
    computer: 1,
    criminalInvestigation: 2,
    evidenceCollection: 3,
    sciences: 2,
    longRangeCombat: 2,
    closeRangeCombat: 1,
    health: 4,
    res: 1,
    cost: 4,
    gameEffect: 'If Agent Kautz is in the Bureau, he may contribute to any EVIDENCE COLLECTION skill check that is occurring in another section of the table.'
  },
  {
    name: 'Detective Hudak',
    image: '/images/xf22-0004x3-detective-hudak.jpg',
    behavioral: 2,
    bureaucracy: 1,
    criminalInvestigation: 2,
    evidenceCollection: 1,
    observation: 1,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 3,
    gameEffect: 'During your Investigation Phase, add 1 to your RP if a Team including Detective Hudak is assigned to a Keyword MONO Site. The cost of any Witness card played at this Site is increased by 1 RP.'
  },
  {
    name: 'Detective John Munch',
    image: '/images/xf22-0005x3-detective-john-munch.jpg',
    behavioral: 2,
    bureaucracy: 2,
    criminalInvestigation: 3,
    evidenceCollection: 2,
    observation: 3,
    subterfuge: 3,
    longRangeCombat: 2,
    closeRangeCombat: 2,
    health: 4,
    res: 1,
    cost: 6,
    gameEffect: 'Place one token on this card. Remove a token when your opponent asks you a penalty question. You may respond with the following phrase: "Aluminum makes a lovely hat."'
  },
  {
    name: 'Agent Hedin',
    image: '/images/xf22-0006x3-agent-hedin.jpg',
    computer: 3,
    criminalInvestigation: 1,
    evidenceCollection: 2,
    sciences: 1,
    longRangeCombat: 1,
    closeRangeCombat: 1,
    health: 3,
    res: 1,
    cost: 3,
    gameEffect: 'Agent Hedin has access to the Field Office Crime Lab. Place one token on this card. Remove a token to draw one Keyword EVIDENCE or EVIDENCE COLLECTION card from your Bureau Deck and add it to your hand. Shuffle your deck.'
  }
];
