import cardList from '~/config/cards.json';

export const cards = cardList.map((card) => ({
  ...card,
  image: `images/${card.set.replaceAll(' ', '-')}/${card.id}.jpg`.toLowerCase()
}));

export const sets = [
  'Premiere',
  'The Truth is Out There',
  '101361',
  '040460',
  'Promo'
];

export const types = [
  'Adversary',
  'Agent',
  'Bluff',
  'Combat',
  'Equipment',
  'Event',
  'Site',
  'Witness',
  'X-File'
];

export const activators = [
  'Active',
  'Active/conspiracy',
  'Adversary',
  'Affiliation',
  'Affiliation site',
  'Agent',
  'Alien',
  'Alien investigation',
  'Behavioral',
  'Believer',
  'Bluff',
  'Briefing',
  'Bureau',
  'Bureaucracy',
  'Combat',
  'Computer',
  'Conspiracy',
  'Creature',
  'Criminal investigation',
  'Event',
  'Evidence collection',
  'Evolutionary',
  'Field',
  'Government',
  'Hospital',
  'Medical',
  'Method site',
  'Motive',
  'Motive site',
  'Move',
  'Multiplayer',
  'Negate',
  'Observation',
  'Occult',
  'Occult adversary',
  'Occult investigation',
  'Pawn',
  'Primordial',
  'Result',
  'Result site',
  'Sciences',
  'Site',
  'Skeptic',
  'Subterfuge',
  'Witness'
];

export const keywords = [
  'Adversary',
  'Affiliation',
  'Agent',
  'Alien',
  'Alien Investigation',
  'Alien Phenomena',
  'Armor',
  'Artifact',
  'Behavioral',
  'Believer',
  'Bluff',
  'Bureaucracy',
  'Combat',
  'Computer',
  'Conspiracy',
  'Creature',
  'Criminal',
  'Criminal Investigation',
  'Electrical',
  'Equipment',
  'Event',
  'Evidence',
  'Evidence Collection',
  'Evolutionary',
  'FBI',
  'Government',
  'Healing',
  'Independent',
  'Killer',
  'Law',
  'Martial Arts',
  'Master',
  'Mechanical',
  'Medical',
  'Method',
  'Mono',
  'Motive',
  'Move',
  'Multi',
  'Mystic',
  'Negate',
  'Neutral',
  'Observation',
  'Occult',
  'Occult Creature',
  'Occult Investigation',
  'Pawn',
  'Phenomena',
  'Primordial',
  'Question',
  'Resource',
  'Result',
  'Sciences',
  'Site',
  'Skeptic',
  'Special',
  'Standard',
  'Subterfuge',
  'Training',
  'Weapon',
  'Weapon Standard',
  'Witness'
];

export const rarities = [
  'Common',
  'Uncommon',
  'Rare',
  'Ultra-Rare',
  'Fixed'
];

export const tags = [
  'Bureau Deck',
  'Combat',
  'Cost',
  'Damage',
  'Discard',
  'Examine',
  'Hand',
  'Long Range Combat',
  'Modify',
  'Negate',
  'Recurring',
  'Reduce',
  'Replenish',
  'Resource',
  'Search',
  'Site',
  'Skill',
  'Skip',
  'Split',
  'Token',
  'Witness'
];
